# Welcome to Jekyll!

# ===============================
# Basic Site Settings
# ===============================
locale: "en-US"
site_theme: "default"
title: "Weijia Liu / Personal Website"
title_separator: "-"
name: &name "Weijia Liu"
description: &description "Ph.D. student at Texas A&M University focusing on 2D materials, sensing, and robotics."
url: "https://weijialiu.github.io"       # ✅ 全小写
baseurl: ""
repository: "toubaojun/weijialiu.github.io"  # ✅ 全小写

# ===============================
# Author Information (sidebar)
# ===============================
author:
  avatar: "profile.png"
  name: "Weijia Liu"
  bio: "Ph.D. student at Texas A&M University, focusing on 2D material-based sensing and robotic applications."
  location: "College Station, TX"
  employer: "Texas A&M University"
  uri: "https://weijialiu.github.io"      # ✅ 全小写
  email: "weijia_liu@tamu.edu"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?user=t33YPscAAAAJ&hl=zh-CN"
  linkedin: "https://www.linkedin.com/in/weijia-liu-08167a322/"
  github: "weijialiu"

# ===============================
# Publication Category
# ===============================
publication_category:
  publications:
    title: 'Publications'

# ===============================
# Site Settings
# ===============================
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# ===============================
# Comments / Feedback
# ===============================
comments:
  provider: false
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

atom_feed:
  hide: true
  path:

# ===============================
# SEO / Analytics (optional)
# ===============================
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image:
og_description:
social:
  type: Person
  name: "Weijia Liu"
  links: []

analytics:
  provider: "false"
  google:
    tracking_id:

# ===============================
# File Handling
# ===============================
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - node_modules
  - README
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# ===============================
# Conversion
# ===============================
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# ===============================
# Markdown Processing
# ===============================
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# ===============================
# Collections — Controls sections like Research, Publications
# ===============================
collections:
  research:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/

# ===============================
# Defaults — Layout rules for each section
# ===============================
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: research
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

# ===============================
# SCSS / Output / Plugins
# ===============================
sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: America/Chicago

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

# ===============================
# Archives & HTML Compression
# ===============================
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development
